### ISSUE TITLE
No crafting recipe and no block drops for 1.21 neoforge

### ISSUE THREAD

**Issue by alescx** [Riewest/SynchronousSwitches#4]
The crafting recipes are not showing up for mc 1.21 and neoforge. also, when breaking the block nothing drops.
anything else works as it should.

**Comment by Riewest** [comment]
Good Catch!

I forgot to rerun the datagen after porting to 1.21.1 and Neoforge.

Should be fixed in the 2.0.1 version I just uploaded to Curseforge.

![image](https://github.com/user-attachments/assets/39a7cca9-4771-4164-9fe3-ebca40243531)
